### ISSUE TITLE
fiss_site_tidy error in bind_rows() issue 

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_elk_2022_reporting#2]
So I got this script to run off the bat. But when I finished inputting all the data I wanted to make sure the script was still working and now it's giving me the bind_rows() error again. I think I know how to fix it now. But everytime I add a mutate line to convert a character it gives me another error. Do I have to convert the entire stream site sheet to fix this? I'll try to reference the line I'm talking about.

**Comment by NewGraphEnvironment** [comment]
fpr::fpr_import_hab_con and fpr::fpr_import_pscis should explicitly spell out the column types vs guessing them from what is in the input spreadsheet it is reading.  This should fix this problem and not result in spreadsheet specific conflicts. I'll reference in `fpr` .  For now - if you can address the issue by mutating to the most rational type between the two conflicting tables that would be great.

**Comment by NewGraphEnvironment** [comment]
For some of the conflicts - another thing that can be done which needs to happen anyway is to populate your habitat_confirmations spreadsheet with the correct type (ex. 00000ELKR for waterbody_id) .  You can see all the types once they are guessed on import by doing something like:

```

test <- fpr::fpr_import_hab_con(backup = F) %>%
    pluck("step_4_stream_site_data")

glimpse(test)

```

As you can see -some of them like `gazetted_names`, `feature_type`, etc. are all good without the calls to mutate

**Comment by Mateo9569** [comment]
Oh ok, I see what's happening now. I must have run the script before I had the `gazetted_names` and `feature_type` fields populated. I got it working now but I still had to mutate four columns. Three of the culprits were populated as logical variables, see https://github.com/NewGraphEnvironment/dff-2022/issues/47#issue-1418625409
