### ISSUE TITLE
electrofishing site names do not contain `ef`

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_elk_2022_reporting#20]
are they actually ef sites or should they be pulled from table 4.3

**Comment by Mateo9569** [comment]
Oh I just realised what you meant by this. There are two site names `197534_us4` and `197534_us5` in table 4.3 that aren't electrofishing sites. Those are the two hab surveys we did upstream of the ford. I can filter those out.
