### ISSUE TITLE
Add reach to the habitat_confirmations.xls and add to tables in results

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_elk_2022_reporting#40]

**Comment by NewGraphEnvironment** [comment]
let's just do it for Weigert for now.  Need it to cross reference FHAP to fish densities

**Comment by Mateo9569** [comment]
Do you want the reach number column included in both tables 4.1 and 4.2 in the results section or just 4.2?
