### ISSUE TITLE
add discharge data summary table to report along with locations to map

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_elk_2022_reporting#42]

**Comment by NewGraphEnvironment** [comment]
@Mateo9569 - where is the script and csv that was used to load the data to the sqlite? If we don't have one thats not a big deal but if we do I can't seem to find it. In an ideal world the raw object has tidy column names and it takes seconds to alter the csv and reload to the sqlite reorganized.....

**Comment by Mateo9569** [comment]
The csv is right [here](https://github.com/NewGraphEnvironment/fish_passage_elk_2022_reporting/blob/main/data/hydrometrics.csv). And the script to import and load to the sqlite is at the end of the tables script. Maybe I should have put it somewhere else. I commented it out so it doesn't drop and reload the object to the sqlite everytime the report is run.

**Comment by Mateo9569** [comment]
Looks like there was a mix up with Brule and Weigert in the csv. Weigert should be Brule and vice versa. I'll fix, re load to sqlite and close this issue.
![image](https://user-images.githubusercontent.com/99455166/223204882-2bdf3264-c451-4486-8453-36a9970e39c3.png)
